# my-fullstack-app/values.yaml
frontend:
  image:
    repository: 975050024946.dkr.ecr.ca-central-1.amazonaws.com/lrcs-frontend
    tag: latest
  service:
    type: ClusterIP
    port: 80

backend:
  image:
    repository: 975050024946.dkr.ecr.ca-central-1.amazonaws.com/lrcs-backend
    tag: latest
  service:
    type: ClusterIP
    port: 8080
  # Environment variable for the backend to connect to MongoDB
  mongodbConnectionString: "mongodb://{{ .Release.Name }}-mongodb:27017/my-database"

mongodb:
  architecture: standalone
  auth:
    # Set the root password first
    rootPassword: "yourStrongPassword"
    # Define custom user/database pairs as lists
    usernames:
      - appuser
    passwords:
      - apppassword123
    databases:
      - my-database
